[build]
  publish = "_site"
  command = "npm run build"
  #command = "npm run build && set -e && find ./_site -type f -name '*.html' -exec staticrypt -f password_template.html {} $PASSWORD -o {} \\;"
  functions = "functions"

[[redirects]]
  from = "/online-vzdelavaci-platformy"
  to = "https://www.zdenek-hejl.com/online-vzdelavaci-platformy"

[[redirects]]
  from = "/tema/*"
  to = "/"

[[redirects]]
  from = "/kategorie/*"
  to = "/"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=63072000; includeSubDomains; preload"
